#ifndef UTEXT_LOGGINGCATEGORIES_H
#define UTEXT_LOGGINGCATEGORIES_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logDebug)
Q_DECLARE_LOGGING_CATEGORY(logInfo)
Q_DECLARE_LOGGING_CATEGORY(logWarning)
Q_DECLARE_LOGGING_CATEGORY(logCritical)

//class loggingcategories {
//
//};


#endif //UTEXT_LOGGINGCATEGORIES_H
